# Generated by Django 3.1.2 on 2020-10-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Prey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('cat1_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Cat1', to='cats.cat')),
                ('cat2_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Cat2', to='cats.cat')),
                ('cat3_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Cat3', to='cats.cat')),
                ('cat4_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Cat4', to='cats.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Hunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('cat_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Cat', to='cats.cat')),
                ('prey_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Prey', to='cats.prey')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Color', to='cats.color'),
        ),
    ]
