# Generated by Django 3.1.2 on 2020-10-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20201030_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usr',
            new_name='User',
        ),
    ]
