# Generated by Django 3.1.2 on 2020-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20201030_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usr',
        ),
    ]
