# Generated by Django 3.1.2 on 2020-11-02 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0007_auto_20201031_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cat_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hunting',
            name='cat_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cat_hunting_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
